routes/web.php
<?php

use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [SiteController::class, 'home'])->middleware('auth');
Route::get('/logout', [SiteController::class, 'logout']);

Route::middleware(['auth', 'admin'])->prefix('/admin')->name('admin.')->group(function() {

    Route::get('/', [AdminController::class, 'index'])->name('index');

    Route::resource('users', \App\Http\Controllers\Admin\UserController::class)->middleware('can:update-users');

    Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);

    Route::resource('products', \App\Http\Controllers\Admin\ProductController::class);

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function roleName()
    {
        switch($this->role) {
            case 0:
                return "User";
            case 1:
                return "Seller";
            case 2:
                return "Admin";
            default:
                return "Inactive";
        }

    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('admin.users.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $request->validate([
            'name'     => ['required', 'max:100'],
            'email'    => ['required', 'email', 'unique:users,email'],
            'password' => ['required', 'min:6', 'max:20'],
            'role'     => ['required', 'numeric', 'min:0', 'max:2'],
        ]);

        $user = new User;
        $user->name = $request->name;
        $user->email = $request->email;
        $user->password = bcrypt($request->password);
        $user->role = $request->role;
        $user->save();

//        User::create($request->only(['name', 'email', 'password', 'role']));

        return redirect()
                ->route('admin.users.index')
                ->with('success', 'User has been added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            'name'     => ['required', 'max:100'],
            'email'    => ['required', 'email', 'unique:users,email,' . $user->id],
            'password' => ['nullable', 'min:6', 'max:20'],
            'role'     => ['required', 'numeric', 'min:0', 'max:2'],
        ]);


        $user->name = $request->name;
        $user->email = $request->email;
        if(!empty($request->password))
            $user->password = bcrypt($request->password);
        $user->role = $request->role;
        $user->save();

//        $user->update($request->only(['name', 'email', 'password', 'role']));

        return redirect()
                ->route('admin.users.index')
                ->with('success', 'User information has been updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(User $user)
    {
        if($user->id == auth()->user()->id)
            return redirect()
                    ->back()
                ->with('error', 'You cannot delete yourself!');

        if($user->role != 0)
            return redirect()
                ->back()
                ->with('error', 'You cannot delete Admin or Seller! Please change their role to User before deleting!');

        $user->delete();

        return redirect()
                ->route('admin.users.index')
                ->with('success', 'User has been deleted successfully!');
    }
}

resources/views/admin/users/create.blade.php
@extends('adminlte::page')

@section('title', 'Add New Users')

@section('plugins.Select2', true)

@section('js')
<script>
    $(document).ready(function() {
        $('#role').select2();
    });
</script>
@endsection
@section('content')

    <x-alert />

    <div class="card">
        <div class="card-header">
            <h3 class="card-title" style="font-size:1.5em;font-weight: bold">Create New User</h3>
            <div class="card-tools">
                <a class="btn btn-success btn-sm" href="{{ route('admin.users.index') }}">
                    <i class="fas fa-arrow-left fa-fw mr-1"></i> Go Back
                </a>
            </div>
        </div>
        <div class="card-body">

            <form action="{{ route('admin.users.store') }}" method="post">
                @csrf

                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @endif" value="{{ old('name') ?? "" }}">
                    @error('name')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email" id="email" class="form-control @error('email') is-invalid @endif" value="{{ old('email') ?? "" }}">
                    @error('email')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="text" name="password" id="password" class="form-control @error('password') is-invalid @endif" value="{{ old('password') ?? "" }}">
                    @error('password')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="role">Role</label>
                    <select name="role" id="role" class="form-control @error('role') is-invalid @endif">
                        <option value="0">User</option>
                        <option value="1">Seller</option>
                        <option value="2">Admin</option>
                    </select>
                    @error('role')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>


                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-user-plus fa-fw mr-1"></i> Create New User
                </button>
            </form>

        </div>
    </div>

@stop

resources/views/admin/users/edit.blade.php
@extends('adminlte::page')

@section('title', 'Add New Users')

@section('plugins.Select2', true)

@section('js')
    <script>
        $(document).ready(function() {
            $('#role').select2();
        });
    </script>
@endsection
@section('content')

    <x-alert />

    <div class="card">
        <div class="card-header">
            <h3 class="card-title" style="font-size:1.5em;font-weight: bold">Edit User: {{ $user->name }}</h3>
            <div class="card-tools">
                <a class="btn btn-success btn-sm" href="{{ route('admin.users.index') }}">
                    <i class="fas fa-arrow-left fa-fw mr-1"></i> Go Back
                </a>
            </div>
        </div>
        <div class="card-body">

            <form action="{{ route('admin.users.update', $user->id) }}" method="post">
                @csrf
                @method('PUT')

                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @endif" value="{{ old('name') ?? $user->name }}">
                    @error('name')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" name="email" id="email" class="form-control @error('email') is-invalid @endif" value="{{ old('email') ?? $user->email }}">
                    @error('email')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="text" name="password" id="password" class="form-control @error('password') is-invalid @endif" value="{{ old('password') ?? "" }}">
                    @error('password')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="role">Role</label>
                    <select name="role" id="role" class="form-control @error('role') is-invalid @endif">
                        <option value="0" @if($user->role == 0) selected @endif>User</option>
                        <option value="1" @if($user->role == 1) selected @endif>Seller</option>
                        <option value="2" @if($user->role == 2) selected @endif>Admin</option>
                    </select>
                    @error('role')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>


                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-user-plus fa-fw mr-1"></i> Update User
                </button>
            </form>

        </div>
    </div>

@stop

resources/views/admin/users/index.blade.php
@extends('adminlte::page')

@section('title', 'Users')

@section('js')
<script type="text/javascript">
function deleteUser(id) {
    if(confirm('Are you sure you want to delete this user?')) {
        document.querySelector('#delete-' + id).submit();
    }
}
</script>
@endsection
@section('content')

    <x-alert />

    <div class="card">
        <div class="card-header">
            <h3 class="card-title" style="font-size:1.5em;font-weight: bold">All Users</h3>
            <div class="card-tools">
                <a class="btn btn-info btn-sm" href="{{ route('admin.users.create') }}">
                    <i class="fas fa-user-plus fa-fw mr-1"></i> Add New
                </a>
            </div>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Role</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>

                @foreach($users as $user)
                <tr>
                    <td>{{ $user->id }}</td>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ $user->roleName() }}</td>
                    <td>
                        <a href="{{ route('admin.users.edit', $user->id) }}">Edit</a>
                    </td>
                    <td>
                        <a href="#" onclick="deleteUser({{ $user->id }})">Delete</a>
                        <form style="display:none" method="POST" id="delete-{{ $user->id }}" action="{{ route('admin.users.destroy', $user->id) }}">
                            @csrf
                            @method('DELETE')
                        </form>
                    </td>
                </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop