routes/web.php
<?php

use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [SiteController::class, 'home'])->middleware('auth');
Route::get('/logout', [SiteController::class, 'logout']);

Route::middleware(['auth', 'admin'])->prefix('/admin')->name('admin.')->group(function() {

    Route::get('/', [AdminController::class, 'index'])->name('index');

    Route::resource('users', \App\Http\Controllers\Admin\UserController::class)->middleware('can:update-users');

    Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);

    Route::resource('products', \App\Http\Controllers\Admin\ProductController::class);

});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $guarded = ['id'];





    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function currentPrice()
    {
        if($this->on_sale)
            return $this->sale_price . " <del>{$this->price}</del>";

        return $this->price;
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Tag;
use App\Models\Media;
use App\Models\Product;
use App\Models\Category;
use App\Models\Attribute;
use Illuminate\Support\Str;
use App\Models\MediaProduct;
use Illuminate\Http\Request;
use App\Models\ProductVariant;
use App\Services\MediaService;
use App\Models\AttributeProduct;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Storage;
use App\Http\Requests\Product\StoreProductRequest;
use App\Http\Requests\Product\UpdateProductRequest;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::paginate(30);

        return view('admin.products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::select(['id', 'name'])->get();

        return view('admin.products.create', compact('categories'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        $request['slug'] = Str::slug($request->slug);
        $request['sku'] = strtoupper(Str::slug($request->sku));

        $request->validate([
            'slug' => 'required|unique:products,slug',
            'sku' => 'required|unique:products,sku',
        ]);

        $product = Product::create([
            'sku' =>  $request->sku,
            'name' => $request->name,
            'slug' => $request->slug,
            'description' => $request->description,
            'price' => $request->price,
            'on_sale' => $request->on_sale ? true : false,
            'sale_price' => $request->sale_price,
            'on_stock' => $request->on_stock ? true : false,
            'min_order_quantity' => $request->min_order_quantity,
            'is_adult' => $request->is_adult ? true : false,
            'remarks' => $request->remarks,
        ]);



        return redirect()
            ->route('admin.products.index')
            ->with('success', 'Products has been added sucessfully!');
    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {

        return view('admin.products.show', compact('product'));
    }
    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('admin.products.edit', compact('product'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProductRequest $request, Product $product)
    {
        $request['slug'] = Str::slug($request->slug);
        $request['sku'] = strtoupper(Str::slug($request->sku));

        $request->validate([
            'slug' => 'required|unique:products,slug,' . $product->id,
            'sku' => 'required|unique:products,sku,' . $product->id,
        ]);

        $product->update([
            'sku' =>  $request->sku,
            'name' => $request->name,
            'slug' => $request->slug,
            'description' => $request->description,
            'price' => $request->price,
            'on_sale' => $request->on_sale ? true : false,
            'sale_price' => $request->sale_price,
            'on_stock' => $request->on_stock ? true : false,
            'min_order_quantity' => $request->min_order_quantity,
            'is_adult' => $request->is_adult ? true : false,
            'remarks' => $request->remarks,
        ]);

        return redirect()
            ->route('admin.products.index')
            ->with('success', 'Product has been updated sucessfully!');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()
            ->route('admin.products.index')
            ->with('success', 'Product has been deleted sucessfully!');
    }




    public function categories(Product $product)
    {
        $categories = Category::all();
        return view('admin.products.categories', compact('product', 'categories'));
    }

    public function addcategories(Request $request, Product $product)
    {
        $request->validate([
            'category_id' => 'required|exists:categories,id'
        ]);

        $product->categories()->attach(Category::find($request->category_id));

        return redirect()
            ->back()
            ->with('sucess', 'Category added sucessfully!');
    }

    public function removecategories(Request $request, Product $product)
    {
        $request->validate([
            'category_id' => 'required|exists:categories,id'
        ]);

        $product->categories()->detach(Category::find($request->category_id));

        return redirect()
            ->back()
            ->with('success', 'Category removed sucessfully!');
    }

    /**
     * Search Products
     *
     * @param Request $request
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View|\Illuminate\Http\RedirectResponse
     */
    public function search(Request $request)
    {
        if (!$request->has('search') || empty($request->search))
            return redirect()->route('admin.products.index');

        $search = $request->search;

        $products = Product::where('name', 'LIKE', '%' . $search . '%')
            ->orwhere('sku', 'LIKE', '%' . $search . '%')
            ->orderBy('id', 'desc')
            ->paginate(30);

        return view('admin.products.index', [
            'search' => true,
            'products' => $products,
            'search_term' => $search,
        ]);
    }

}

resources/views/admin/products/create.blade.php
@extends('adminlte::page')

@section('title', 'Add New Product')

@section('plugins.Select2', true)

@section('js')
    <script>
        $(document).ready(function () {
            $('#categories').select2();

        });
    </script>
@endsection

@section('content')

    <x-alert/>

    <div class="card">
        <div class="card-header">
            <h3 class="card-title" style="font-size:1.5em;font-weight: bold">Add New Product</h3>
            <div class="card-tools">
                <a class="btn btn-success btn-sm" href="{{ route('admin.products.index') }}">
                    <i class="fas fa-arrow-left fa-fw mr-1"></i> Go Back
                </a>
            </div>
        </div>
        <form action="{{ route('admin.products.store') }}" method="post">
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <label for="sku" title="Stock Keeping Unit">SKU <span title="Required" class="text-danger">*</span></label>
                    <input type="text" name="sku" id="sku" class="form-control @error('sku') is-invalid @endif"
                           value="{{ old('sku') ?? "" }}" autofocus>

                    @error('sku')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="name">Name <span title="Required" class="text-danger">*</span></label>
                    <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @endif"
                           value="{{ old('name') ?? "" }}">

                    @error('name')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="slug">Slug <span title="Required" class="text-danger">*</span></label>
                    <input type="text" name="slug" id="slug" class="form-control @error('slug') is-invalid @endif"
                           value="{{ old('slug') ?? "" }}">

                    @error('slug')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="name">Description</label>
                    <textarea name="description" id="description"
                              class="form-control @error('description') is-invalid @endif">{{ old('description') ?? "" }}</textarea>

                    @error('description')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="price">Price <span title="Required" class="text-danger">*</span></label>
                    <input type="number" name="price" id="price" class="form-control @error('price') is-invalid @endif"
                           value="{{ old('price') ?? "" }}">

                    @error('price')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <div class="icheck-primary">
                        <input type="checkbox" name="on_sale" id="on_sale" value="1" @if(old('on_sale')) checked @endif>
                        <label for="on_sale">Product is on sale?</label>
                    </div>

                    @error('on_sale')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="sale_price">Sale Price</label>
                    <input type="number" name="sale_price" id="sale_price"
                           class="form-control @error('sale_price') is-invalid @endif"
                           value="{{ old('sale_price') ?? "" }}">

                    @error('sale_price')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>
            </div>
            <div class="card-footer">
                <h3 class="card-title" style="font-size:1.5em;font-weight: bold">Extra Details</h3>
            </div>
            <div class="card-body">
                <div class="form-group">
                    <label for="min_order_quantity">Minimum Order Quantity</label>
                    <input type="text" name="min_order_quantity" id="min_order_quantity"
                           class="form-control @error('min_order_quantity') is-invalid @endif"
                           value="{{ old('min_order_quantity') ?? 0 }}">

                    @error('min_order_quantity')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <div class="icheck-primary">
                        <input type="checkbox" name="on_stock" id="on_stock" value="1" checked>
                        <label for="on_stock">Product is on Stock?</label>
                    </div>

                    @error('on_stock')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>



                    @error('is_adult')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group row mb-0">
                    <div class="form-group col-12 col-md-6">
                        <label for="categories">Categories</label>
                        <select
                            name="categories[]" id="categories"
                            class="form-control @error('categories') is-invalid @endif"
                            multiple="multiple"
                        >
                            @foreach($categories as $item)
                                <option @if(in_array($item->id, old('categories') ?? [])) selected
                                        @endif value="{{ $item->id }}">{{ $item->name }}</option>
                            @endforeach
                        </select>

                        @error('categories')
                        <small class="form-text text-danger">{{ $message }}</small>
                        @enderror
                    </div>


                </div>

                <div class="form-group">
                    <label for="remarks">Remarks <small><em></em></small></label>
                    <textarea name="remarks" id="remarks"
                              class="form-control @error('remarks') is-invalid @endif">{{ old('remarks') ?? "" }}</textarea>

                    @error('remarks')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-plus fa-fw mr-1"></i> Create New Product
                </button>
                <a href="{{ route('admin.products.index') }}" class="btn btn-link float-right"> Cancel</a>
            </div>

        </form>
    </div>

@stop

resources/views/admin/products/edit.blade.php
@extends('adminlte::page')

@section('title', 'Update Product')

@section('content')

    <x-alert/>

    <div class="card">
        <div class="card-header">
            <h3 class="card-title" style="font-size:1.5em;font-weight: bold">Update Product</h3>
            <div class="card-tools">
                <a class="btn btn-success btn-sm" href="{{ route('admin.products.index') }}">
                    <i class="fas fa-arrow-left fa-fw mr-1"></i> Go Back
                </a>
            </div>
        </div>
        <div class="card-body">

            <form action="{{ route('admin.products.update', $product->id) }}" method="post">
                @csrf
                @method('PUT')

                <div class="form-group">
                    <label for="sku">SKU</label>
                    <input
                        type="text"
                        name="sku" id="sku"
                        class="form-control @error('sku') is-invalid @endif"
                        value="{{ old('sku') ?? $product->sku }}"
                        autofocus
                    >
                    @error('sku')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="name">Name</label>
                    <input
                        type="text"
                        name="name" id="name"
                        class="form-control @error('name') is-invalid @endif"
                        value="{{ old('name') ?? $product->name }}"
                    >

                    @error('name')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="slug">Slug <span title="Required" class="text-danger">*</span></label>
                    <input
                        type="text"
                        name="slug"
                        id="slug"
                        class="form-control @error('slug') is-invalid @endif"
                        value="{{ old('slug') ?? $product->slug }}"
                    >

                    @error('slug')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>


                <div class="form-group">
                    <label for="name">Description</label>
                    <textarea
                        name="description" id="description"
                        class="form-control @error('description') is-invalid @endif"
                    >{{ old('description') ?? $product->description }}</textarea>

                    @error('description')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>


                <div class="form-group">
                    <label for="price">Price</label>
                    <input
                        type="number"
                        name="price" id="price"
                        class="form-control @error('price') is-invalid @endif"
                        value="{{ old('price') ?? $product->price }}"
                    >

                    @error('price')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>


                <div class="form-group">
                    <label for="on_sale">
                        <input
                            type="checkbox"
                            name="on_sale" id="on_sale"
                            value="1" @if(old('on_sale') || $product->on_sale) checked @endif
                        >
                        <span>On Sale ?</span>
                    </label>

                    @error('on_sale')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>


                <div class="form-group">
                    <label for="sale_price">Sale Price</label>
                    <input
                        type="number"
                        name="sale_price" id="sale_price"
                        class="form-control @error('sale_price') is-invalid @endif"
                        value="{{ old('sale_price') ?? $product->sale_price }}"
                    >

                    @error('sale_price')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>


                <div class="form-group">
                    <label for="on_stock">
                        <input
                            type="checkbox"
                            name="on_stock" id="on_stock"
                            value="1" @if(old('on_stock') || $product->on_stock) checked @endif
                        >
                        <span>On Stock ?</span>
                    </label>

                    @error('on_stock')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="min_order_quantity">Minimum Order Quantity</label>
                    <input
                        type="number"
                        name="min_order_quantity" id="min_order_quantity"
                        class="form-control @error('min_order_quantity') is-invalid @endif"
                        value="{{ old('min_order_quantity') ?? $product->min_order_quantity}}"
                    >

                    @error('min_order_quantity')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="is_adult">
                        <input
                            type="checkbox"
                            name="is_adult" id="is_adult"
                            value="1" @if(old('is_adult') || $product->is_adult) checked @endif
                        >
                        <span>Is Adult ?</span>
                    </label>
                    @error('is_adult')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="remarks">Remarks</label>
                    <textarea
                        name="remarks" id="remarks"
                        class="form-control @error('remarks') is-invalid @endif"
                    >{{ old('remarks') ?? $product->remarks}}</textarea>

                    @error('remarks')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>


                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-edit fa-fw mr-1"></i> Update Product
                </button>
                <a href="{{ route('admin.products.index') }}" class="btn btn-link float-right"> Cancel</a>
            </form>

        </div>
    </div>

@stop

resources/views/admin/products/index.blade.php
@extends('adminlte::page')

@section('title', 'Products')

@section('content')

    <x-alert/>
    <x-delete/>

    <div class="card">

        <div class="card-body p-0">
            <table class="table table-bordered border-top-0">
                <thead class="thead-dark">
                <tr>
                    <th>ID</th>
                    <th>SKU</th>
                    <th>Name</th>
                    <th>Price</th>
                    <th style="width: 275px">Action</th>
                </tr>
                </thead>
                <tbody>

                @foreach($products as $product)
                    <tr>
                        <td>{{ $product->id }}</td>
                        <td>{{ $product->sku }}</td>
                        <td>{{ $product->name }}</td>
                        <td>{!! $product->currentprice() !!}</td>
                        <td>
                            <a href="{{ route('admin.products.show',$product->id) }}" class="btn btn-sm btn-primary">
                                <i class="fas fa-fw fa-eye mr-1"></i> Show
                            </a>

                            <a href="{{route('admin.products.edit',$product->id)}}"
                               class="ml-1 btn btn-sm btn-secondary">
                                <i class="fas fa-fw fa-edit mr-1"></i> Edit
                            </a>

                            <a href="#" onclick="confirmDelete({{$product->id}})" class="ml-1 btn btn-sm btn-danger">
                                <i class="fas fa-fw fa-trash mr-1"></i> Delete
                            </a>

                            <form style="display:none" method="POST" id="delete-form-{{ $product->id }}"
                                  action="{{ route('admin.products.destroy', $product->id) }}">
                                @csrf
                                @method('DELETE')
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            @if(count($products) == 0)
                <div class="alert alert-warning mb-0 text-center" style="border-radius: 0">
                    @if(!empty($search))
                        There are no products matching your search term. Please change your search term to something else.
                    @else
                        There are no products registered on the system. Please add some and it will appear here!
                    @endif
                </div>
            @endif
        </div>

        @if($products->total() > 30)
            <div class="card-footer">
                {{ $products->links() }}
            </div>
        @endif

    </div>
@stop

resources/views/admin/products/show.blade.php
@extends('adminlte::page')

@section('title', 'Product')

@section('js')
    <script type="text/javascript">
        function deleteTag(id) {
            if (confirm('Are you sure you want to delete this tag?')) {
                document.querySelector('#delete-' + id).submit();
            }
        }
    </script>
@endsection

@section('content')

    <div class="card">
        <div class="card-header">
            <h3 class="card-title" style="font-size:1.5em;font-weight: bold">
                Product Info
            </h3>
            <div class="card-tools">



                    <i class="fas fa-clipboard-list mr-1"></i> Categories
                </a>






                <a class="btn btn-success btn-sm" href="{{ route('admin.products.index') }}">
                    <i class="fas fa-arrow-left fa-fw mr-1"></i> Go Back
                </a>
            </div>
        </div>

        <div class="card-body p-0">

            <table class="table table-bordered">
                <tr>
                    <th>ID/SKU</th>
                    <td>{{ $product->id }} / {{ $product->sku }}</td>
                </tr>
                <tr>

                    <th>Name</th>
                    <td><b>{{ $product->name }}</b></td>
                </tr>
                <tr>
                    <th>Price</th>
                    <td>{{ env("APP_CURRENCY", "Rs.") }} {{ $product->price }}</td>
                </tr>
                <tr>
                    <th>On Sale?</th>
                    <td>{{ $product->on_sale ? "Yes" : "No" }}</td>
                </tr>
                @if($product->on_sale)
                    <tr>
                        <th>Sale Price</th>
                        <td>{{ env("APP_CURRENCY", "Rs.") }} {{ $product->sale_price }}</td>
                    </tr>
                @endif
                <tr>
                    <th>Description</th>
                    <td>{{ $product->description }}</td>
                </tr>
                @if($product->min_order_quantity)
                    <tr>
                        <th>Minimum Order</th>
                        <td>{{ $product->min_order_quantity }}</td>
                    </tr>
                @endif




            </table>
        </div>
    </div>
@stop