routes/web.php
<?php

use App\Http\Controllers\SiteController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\AdminController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/home', [SiteController::class, 'home'])->middleware('auth');
Route::get('/logout', [SiteController::class, 'logout']);

Route::middleware(['auth', 'admin'])->prefix('/admin')->name('admin.')->group(function() {

    Route::get('/', [AdminController::class, 'index'])->name('index');

    Route::resource('users', \App\Http\Controllers\Admin\UserController::class)->middleware('can:update-users');

    Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);

    Route::resource('products', \App\Http\Controllers\Admin\ProductController::class);

});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'slug', 'category_id'];

    public function categories()
    {
        return $this->hasMany(Category::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }


    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::with('category')->get();

        return view('admin.categories.index', compact('categories'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();

        return view('admin.categories.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'slug' => 'required|unique:categories,slug',
            'category_id' => 'nullable|exists:categories,id'
        ]);

        Category::create($request->only(['name', 'slug', 'category_id']));

        return redirect()
                ->route('admin.categories.index')
                ->with('success', 'Category has been added successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        // $category = Category::with(['categories', 'category'])->get();

        return view('admin.categories.show', compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $categories = Category::all();

        return view('admin.categories.edit', compact('category', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        $request->validate([
            'name' => 'required',
            'slug' => 'required|unique:categories,slug,' . $category->id,
            'category_id' => 'nullable|exists:categories,id'
        ]);

        $category->update($request->only(['name', 'slug', 'category_id']));

        return redirect()
                ->route('admin.categories.index')
                ->with('success', 'Category information has been updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()
                ->route('admin.categories.index')
                ->with('success', 'Category has been deleted successfully!');
    }
}

resources/views/admin/categories/create.blade.php
@extends('adminlte::page')

@section('title', 'Add New Category')

@section('plugins.Select2', true)

@section('js')
<script>
    $(document).ready(function() {
        $('#category_id').select2();
    });
</script>
@endsection
@section('content')

    <x-alert />

    <div class="card">
        <div class="card-header">
            <h3 class="card-title" style="font-size:1.5em;font-weight: bold">Create New Category</h3>
            <div class="card-tools">
                <a class="btn btn-success btn-sm" href="{{ route('admin.categories.index') }}">
                    <i class="fas fa-arrow-left fa-fw mr-1"></i> Go Back
                </a>
            </div>
        </div>
        <div class="card-body">

            <form action="{{ route('admin.categories.store') }}" method="post">
                @csrf

                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @endif" value="{{ old('name') ?? "" }}">
                    @error('name')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="slug">Slug</label>
                    <input type="text" name="slug" id="slug" class="form-control @error('slug') is-invalid @endif" value="{{ old('slug') ?? "" }}">
                    @error('slug')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="category_id">Parent Category</label>
                    <select name="category_id" id="category_id" class="form-control @error('category_id') is-invalid @endif">
                        <option value="">No Parent</option>
                        @foreach($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->name }}</option>
                        @endforeach
                    </select>
                    @error('category_id')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>


                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-user-plus fa-fw mr-1"></i> Create New Category
                </button>
            </form>

        </div>
    </div>

@stop

resources/views/admin/categories/edit.blade.php
@extends('adminlte::page')

@section('title', 'Edit Category')

@section('plugins.Select2', true)

@section('js')
<script>
    $(document).ready(function() {
        $('#category_id').select2();
    });
</script>
@endsection
@section('content')

    <x-alert />

    <div class="card">
        <div class="card-header">
            <h3 class="card-title" style="font-size:1.5em;font-weight: bold">Edit Category: {{ $category->name }}</h3>
            <div class="card-tools">
                <a class="btn btn-success btn-sm" href="{{ route('admin.categories.index') }}">
                    <i class="fas fa-arrow-left fa-fw mr-1"></i> Go Back
                </a>
            </div>
        </div>
        <div class="card-body">

            <form action="{{ route('admin.categories.update', $category->id) }}" method="post">
                @csrf
                @method('PUT')

                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @endif" value="{{ old('name') ?? $category->name }}">
                    @error('name')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="slug">Slug</label>
                    <input type="text" name="slug" id="slug" class="form-control @error('slug') is-invalid @endif" value="{{ old('slug') ?? $category->slug }}">
                    @error('slug')
                    <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="category_id">Parent Category</label>
                    <select name="category_id" id="category_id" class="form-control @error('category_id') is-invalid @endif">
                        <option value="">No Parent</option>
                        @foreach($categories as $cat)
                        <option
                            value="{{ $cat->id }}"
                            @if($category->category_id == $cat->id ) selected @endif
                        >{{ $cat->name }}</option>
                        @endforeach
                    </select>
                    @error('category_id')
                        <small class="form-text text-danger">{{ $message }}</small>
                    @enderror
                </div>


                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-user-plus fa-fw mr-1"></i> Update Category
                </button>
            </form>

        </div>
    </div>

@stop

resources/views/admin/categories/index.blade.php
@extends('adminlte::page')

@section('title', 'Categories')

@section('js')
<script type="text/javascript">
function deleteCategory(id) {
    if(confirm('Are you sure you want to delete this category?')) {
        document.querySelector('#delete-' + id).submit();
    }
}
</script>
@endsection
@section('content')

    <x-alert />

    <div class="card">
        <div class="card-header">
            <h3 class="card-title" style="font-size:1.5em;font-weight: bold">All Categories</h3>
            <div class="card-tools">
                <a class="btn btn-info btn-sm" href="{{ route('admin.categories.create') }}">
                    <i class="fas fa-plus-circle fa-fw mr-1"></i> Add New
                </a>
            </div>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Parent</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
                <tbody>

                @foreach($categories as $category)
                <tr>
                    <td>{{ $category->id }}</td>
                    <td>
                        <a href="{{ route('admin.categories.show', $category->id) }}">{{ $category->name }}</a>
                    </td>
                    <td>
                        {{ $category->slug }}
                    </td>
                    <td>
                        @if($category->category_id)
                        <a href="{{ route('admin.categories.show', $category->category_id) }}">{{ $category->category->name }}</a>
                        @endif
                    </td>

                    <td>
                        <a href="{{ route('admin.categories.edit', $category->id) }}">Edit</a>
                    </td>
                    <td>
                        <a href="#" onclick="deleteCategory({{ $category->id }})">Delete</a>
                        <form style="display:none" method="POST" id="delete-{{ $category->id }}" action="{{ route('admin.categories.destroy', $category->id) }}">
                            @csrf
                            @method('DELETE')
                        </form>
                    </td>
                </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
@stop

resources/views/admin/categories/show.blade.php
@extends('adminlte::page')

@section('title', 'Categories')

@section('content')

    <div class="card">
        <div class="card-header">
            <h3 class="card-title" style="font-size:1.5em;font-weight: bold">Category: {{ $category->name }}</h3>
            <div class="card-tools">
                <a class="btn btn-success btn-sm" href="{{ route('admin.categories.index') }}">
                    <i class="fas fa-arrow-left fa-fw mr-1"></i> Go Back
                </a>
            </div>
        </div>
        <div class="card-body">

            <table class="table table-bordered">

                <tr>
                    <td>ID:</td>
                    <td>{{ $category->id }}</td>
                </tr>
                <tr>
                    <td>Name:</td>
                    <td>{{ $category->name }}</td>
                </tr>
                <tr>
                    <td>Slug:</td>
                    <td>{{ $category->slug }}</td>
                </tr>
                <tr>
                    <td>Parent Category: </td>
                    <td>
                        @if($category->category_id)
                        <a href="{{ route('admin.categories.show', $category->category_id) }}">{{ $category->category->name }}</a>
                        @else
                            No Parent
                        @endif
                    </td>
                </tr>

                <tr>
                    <td>Child Categories:</td>
                    <td>
                        @if(count($category->categories) > 0)

                        <ul>
                            @foreach($category->categories as $child)
                            <li>
                                <a href="{{ route('admin.categories.show', $child->id) }}">
                                    {{ $child->name }}
                                </a>
                            </li>
                            @endforeach
                        </ul>

                        @endif
                    </td>
                </tr>

            </table>


        </div>
    </div>
@stop